### PR TITLE
This commit fulfills someone's request to be removed

### LINKED ISSUE #399: Right to be forgotten
Please remove my name from current editions of this specification.  You are free to remove my name from everything but I am directly and unambiguously asking for my name to be remove as an "Author" of the current edition.

### PR DESCRIPTION
**Pull request by ProgramMax**
Closes #399

### CODE REVIEW

**Review by jbowler — APPROVED** [review]
Thankyou.

**Comment by jbowler** [comment]
Still waiting.

**Comment by ProgramMax** [comment]
I cannot merge this pull request until @svgeesus approves it.
Unfortunately, you sent the request right during the holidays, when people are likely on vacation.

**Review by svgeesus — APPROVED** [review]
LGTM

**Comment by svgeesus** [comment]
I'm on vacation and with intermittent connectivity.

@ProgramMax could you review my https://github.com/w3c/PNG-spec/pull/397 which has been waiting for a couple of weeks? It is the same as https://github.com/w3c/PNG-spec/pull/378 except without trampling on 49 unrelated files :)

**Pull request merged**
