### PR TITLE
Not currently an ISO standard, fix #79

### LINKED ISSUE #79: ISO/IEC 15948:2003 (E)
The Editors Draft, which is derived from the PNG Second Edition W3C Recommendation, still claims to be

> Information technology — Computer graphics and image processing — Portable Network Graphics (PNG): Functional specification. ISO/IEC 15948:2003 (E)

As this is no longer true, we should remove this subheading. We should also change all occurrences of "this International Standard to "this specification".

Once the evental Third Edition Recommendation gets submitted to ISO as a PAS it will have a new number.

### PR DESCRIPTION
**Pull request by svgeesus**

### CODE REVIEW

**Comment by ProgramMax** [comment]
Is the intention here to undo this change once ISO approves the change?

**Review by ProgramMax — APPROVED** [review]
LGTM

**Comment by svgeesus** [comment]
Once submitted to ISO it would have a different number and possibly a different (sub)title.

**Comment by ProgramMax** [comment]
Sounds good

**Pull request merged**
