### PR TITLE
Not a separate spec, fix #317

### LINKED ISSUE #317: APNG section reads like a separate spec
The APNG section talks about PNGs as if they are part of a separate spec. This makes sense, since the APNG wording comes from a separate spec.

Changing the wording to sound like it is all the same spec is not critical but would be nice.

### PR DESCRIPTION
**Pull request by svgeesus**
Hopefully this is clearer?

### CODE REVIEW

**Review by ProgramMax — APPROVED** [review]
LGTM

**Comment by chrisn** [comment]
This change looks good. There are a couple of other places I noticed in this section that talk about the PNG spec as if it were a separate thing, that could possibly be rephrased:

* 4.9.1 has "as defined in previous versions of the PNG Specification" (do we still need to say this?)
* 4.9.2 has "since the PNG specification does not impose ordering restrictions on ancillary chunks" and describes sequence numbers in fcTL and fdAT chunks. To avoid potential duplication, could these be integrated into the relevant subsections of 11.3?

**Comment by svgeesus** [comment]
> 4.9.1 has "as defined in previous versions of the PNG Specification" (do we still need to say this?)

I think so, because this is not new for the Web but is new in PNG Third Edition.

> 4.9.2 has "since the PNG specification does not impose ordering restrictions on ancillary chunks" and describes sequence numbers in fcTL and fdAT chunks. To avoid potential duplication, could these be integrated into the relevant subsections of 11.3?

Interesting point. However 4.9 is describing the _concept_ of a sequence number (so belongs in 4.x Concepts) , while this would need to be duplicated if explained inside `fcTL` and `fdAT`. So I feel the current ordering is better.

**Comment by ProgramMax** [comment]
I agree with @chrisn on the 4.9.2 part of "since the PNG specification does not...". It sounds like it is talking in third person.
Although, it works. The alternate might be "since this specification does not...", which doesn't sound much better.
So I'm okay with it as-is.

**Comment by svgeesus** [comment]
"this specification" does indeed read better

**Comment by svgeesus** [comment]
See PR https://github.com/w3c/PNG-spec/pull/328

**Pull request merged**
